Import('env')


cpppath      = ['./src']
libpath      = ['.']
cppflags     = ['-Werror', '-Wall', '-Wextra']


# env.Append(CPPFLAGS = cppflags)
# env.Append(CPPPATH = cpppath)
# env.Append(LIBPATH = libpath)


source_files = ['main.cpp', 'player.cpp', 'card.cpp', 'deck.cpp', 'board.cpp']

env.VariantDir('build', 'src', duplicate=0)

src = env.Library('../player', source_files)

env.Program('../player', source_files)

Return('src')