Import('env eval')
env = env.Clone()



# env.Append(CPPFLAGS = cppflags)
# env.Append(CPPPATH = cpppath)
# env.Append(LIBPATH = libpath)


common_libs = ['pthread']
boost_libs = ['boost_program_options', 'boost_system']

libs = [common_libs, boost_libs, eval]

env.Append(LIBS = libs)


source_files = ['main.cpp', 'player.cpp', 'card.cpp', 'deck.cpp', 'board.cpp']

env.VariantDir('build', 'src', duplicate=0)

src = env.Library('../player', source_files)

env.Program('../player', source_files)

Return('src')