Import('env', 'src')

env = env.Clone()


cpppath      = ['#/src']
libpath      = ['../']

common_libs = ['pthread']
boost_libs = ['boost_program_options', 'boost_system']

libs = [common_libs, boost_libs]

cppflags     = ['-Werror', '-Wall', '-Wextra']

env.Append(LIBS = [libs, src])
env.Append(LIBPATH = libpath)
#env.Append(CPPPATH = cpppath)


# env.Append(CPPFLAGS = cppflags)


source_files = ['main.cpp']

#env.VariantDir('build', 'src', duplicate=0)

src = env.Program(target='test', source=source_files)

